### ISSUE TITLE
crash due to recent changes: app.log is not a function

### ISSUE THREAD

**Issue by josep-llodra** [robvanderleek/create-issue-branch#847]
Could be related to this commit: https://github.com/robvanderleek/create-issue-branch/commit/96a776df64cd90ee2f98a12d261f67948702dcd1

Stack trace:

```
Run robvanderleek/create-issue-branch@main
TypeError: app.log is not a function
    at __webpack_modules__.71890.exports.default (/home/runner/work/_actions/robvanderleek/create-issue-branch/main/dist/index.js:1203:9)
    at Probot.load (/home/runner/work/_actions/robvanderleek/create-issue-branch/main/dist/index.js:3971[4
    at run (/home/runner/work/_actions/robvanderleek/create-issue-branch/main/dist/index.js:162647:16)
(/home/runner/work/_actions/robvanderleek/create-issue-branch/main/dist/index.js:34:1)
    at __nccwpck_require__ (/home/runner/work/_actions/robvanderleek/create-issue-branch/main/dist/index.js:1[6]    at /home/runner/work/_actions/robvanderleek/create-issue-branch/main/dist/index.js:163026:37
    at Object.<anonymous> (/home/runner/work/_actions/robvanderleek/create-issue-branch/main/dist/index.js:163029:12)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:12[9]
    at Module.load (node:internal/modules/cjs/loader:1091:32)
```

Thanks in advance!

**Comment by flamisz** [comment]
same for me

**Comment by flamisz** [comment]
thanks @robvanderleek
